
const BD = [
    {country: 'France', challenge: 'Quais cidades são Francesas?', Translator: 'Quelles villes sont françaises?', Options: Array(2), response: 'Lyon'},
    {country: 'France', challenge: 'Em qual cidade existiu o primeiro cinema do mundo?', Translator: 'Dans quelle ville était le premier cinéma du monde ?', Options: Array(2), response: 'La Ciotat'},
    {country: 'France', challenge: 'Comida Típica Francesa?', Translator: 'Cuisine Française Typi que?', Options: Array(2), response: 'Ratatouille'},
    {country: 'France', challenge: 'Onde Luiz XV morava?', Translator: 'Où Louis XV a-t-il vécu ?', Options: Array(2), response: 'Castelo de Versalhes'},
    {country: 'France', challenge: 'Qual animal representa a França?', Translator: 'Quel animal représente la France?', Options: Array(2), response: 'Galo'},
    {country: 'Canada', challenge: 'Comida típica do Quebec?', Translator: 'Cuisine québécois Typique?', Options: Array(2), response: 'Poutine'},
    {country: 'Canada', challenge: 'Qual o animal que representa o Canada?', Translator: 'Quel animal représente le Canada?', Options: Array(2), response: 'Castor'},
    {country: 'Canada', challenge: 'Onde nasceu o Circo du Soleil?', Translator: 'Où est né le Cirque du Soleil ?', Options: Array(2), response: 'Montreal'},
    {country: 'Canada', challenge: 'Onde nasceu o Circo du Soleil?', Translator: 'Où est né le Cirque du Soleil ?', Options: Array(2), response: 'Montreal'},
    {country: 'Belgique', challenge: 'Quais as duas comidas  de origem Belga mais famosas?', Translator: 'Quels sont les deux plats belges les plus connus ???', Options: Array(2), response: 'Chocolate e Batata-Frita'},
    {country: 'Belgique', challenge: 'Qual país acontece o Tomorrowland?', Translator: 'Dans quel pays se   déroule Tomorrowland ?', Options: Array(2), response: 'Belgique'},
    {country: 'Belgique', challenge: 'Quais cidades são Belgas?', Translator: 'Quelles villes sont Belgique?', Options: Array(2), response: 'Boom'},
    {country: 'B elgique', challenge: 'Quem nasce na Belgica é?', Translator: 'Qui est né en Belgique ??', Options: Array(2), response: 'Belga'},
    {country: 'H aïti', challenge: 'Qual a capital do Haïti?', Translator: "Quelle est la capitale d'Haïti ?", Options: Array(2), response: 'Porto Principe'},
    {country: 'Haïti', challenge: 'Qual o continente que fica o Haïti?', Translator: 'Sur quel continent se trouve Haïti?', Options: Array(2), response: 'América Central'},
    {country: 'Haïti', challenge: 'Quais as cores principais da bandeira do Haïti?', Translator: 'Quelles sont les principales couleurs du drapeau Haïtien?', Options: Array(2), response: 'Azul e Vermelho'},
    {country: 'Suisse', challenge: 'Qual o formato da bandeira da Suisse?', Translator: 'Quelle est la forme du drapeau suisse?', Options: Array(2), response: 'Q uadrada'},
    {country: 'Suisse', challenge: 'Qual a Capital da Suisse?', Translator: 'Quelle est la capitale de la Suisse?', Options: Array(2), response: 'Berna'},
    {country: 'Suisse', challenge: 'Qual comida foi criada na Suisse?', Translator: 'Quelle nourriture a été créée en Suisse?', Options: Array(2), response: 'C hocolate'},
    {country: 'Suisse', challenge: 'Qual a Capital da Suisse?', Translator: 'Quelle est la capitale de la Suisse?', Options: Array(2), response: 'Berna'},
    {country: 'Suisse', challenge: 'Qual festival é típico da Suisse?', Translator: 'Quelle fête est typique de la Suisse?', Options: Array(2), response: 'Festival de Iodele'},
    {country: 'Suisse', challenge: 'Qual desses pensadores é Suíço?', Translator: 'Lequel de ces penseurs est suisse ??', Options: Array(2), response: 'Jean-Jacques Rosseau'},
]

